// Type definitions for the Vibebase generated client (lib/backplane.mjs).
// Generated by Vibebase — gives your TypeScript editor full autocomplete + checking.

export interface Sql {
  (strings: TemplateStringsArray, ...values: unknown[]): Promise<any[]>;
  query(text: string, params?: unknown[]): Promise<any[]>;
}
export const sql: Sql;

export interface User { id: string; email: string }
export interface Session { user: User; token: string }

// Auth
export function signUp(email: string, password: string): Promise<Session>;
export function signIn(email: string, password: string): Promise<Session>;
export function getUser(token: string): Promise<User | null>;
export function signOut(token: string): Promise<void>;
export function signOutAll(userId: string): Promise<void>;
export function requestPasswordReset(email: string): Promise<string | null>;
export function resetPassword(token: string, newPassword: string): Promise<{ user: User }>;
export function requestEmailVerification(email: string): Promise<string | null>;
export function verifyEmail(token: string): Promise<{ user: User & { email_verified: boolean } }>;

// Social login
export type OAuthProvider = 'google' | 'github';
export function oauthRedirectUrl(provider: OAuthProvider, conf?: { clientId?: string; redirectUri?: string; state?: string; scope?: string }): string;
export function oauthCallback(provider: OAuthProvider, code: string, conf?: { clientId?: string; clientSecret?: string; redirectUri?: string }): Promise<Session>;

// Vector search
export function addDocument(content: string, embedding: number[], metadata?: Record<string, unknown>): Promise<string>;
export function searchSimilar(embedding: number[], k?: number): Promise<Array<{ id: string; content: string; metadata: Record<string, unknown>; similarity: number }>>;

// File storage
export function putFile(key: string, bytes: Uint8Array | string, contentType?: string): Promise<{ key: string; size: number; contentType: string }>;
export function getFile(key: string): Promise<{ key: string; contentType: string; size: number; bytes: Uint8Array } | null>;
export function deleteFile(key: string): Promise<void>;
export function listFiles(prefix?: string): Promise<Array<{ key: string; content_type: string; size: number; created_at: string }>>;

// Change feed
export function changesSince(table: string, opts?: { column?: string; since?: unknown; limit?: number }): Promise<any[]>;
export function onChange(table: string, handler: (rows: any[]) => void, opts?: { column?: string; since?: unknown; intervalMs?: number }): () => void;

// Migrations + bulk load
export function migrate(dir?: string): Promise<string[]>;
export function insertMany(table: string, rows: Record<string, unknown>[], opts?: { chunkSize?: number; onConflict?: string }): Promise<number>;
